### ISSUE TITLE
Build failed with latest Activator Version 1.3.7

### ISSUE THREAD

**Issue by sriramkp** [JAVEO/clustered-chat#6]
Please help me in resolving the below issue.

Examining project/play.sbt
Examining project/plugins.sbt
Examining project/play-fork-run.sbt
Using Play 2.4.3 -> OK
Lost or failed sbt connection: Connection closed
Loading project definition from D:\Play\clustered-chat\project
Set current project to Clustered chat (in build file:/D:/Play/clustered-chat/)
com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
Use 'last' for the full log.
Failed to load project.

**Comment by bartekkalinka** [comment]
You need at least java 7 in your path. Or 8.

**Comment by MarcinBurczak** [comment]
Play framework required java 8

**Comment by sriramkp** [comment]
Iam using Java 8. And Iam able to compile other projects.

**Comment by sergiuszkierat** [comment]
@sriramkp,
- Do the other projects require JDK 8? Which other activator do you mean?
- Could you check/provide your _$JAVA_HOME_ envirionment variable?

I would like to invite you to our [gitter's channel](https://gitter.im/JAVEO/clustered-chat)

**Comment by sriramkp** [comment]
I am extremely sorry for taking your time. Its working fine now. 
Yes, its due to the $JAVA_HOME is pointing to Java7.

**Comment by sriramkp** [comment]
Now Iam getting the below run time error. It will be great if you could help me.

Setting up Play fork run ... (use Ctrl+D to cancel)
scala.pickling.PicklingException: Not a primitive: scala.Nothing, found JNothing
    at sbt.serialization.json.VerifyingJSONPickleReader.sbt$serialization$json$VerifyingJSONPickleReader$$unpickleHelper$1(JSONPickleFormat.scala:367)
    at sbt.serialization.json.VerifyingJSONPickleReader.readPrimitive(JSONPickleFormat.scala:373)
    at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:28)
    at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler$macro$14$2$.unpickle(Serializers.scala:73)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
    at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler$macro$14$2$.unpickleEntry(Serializers.scala:73)
    at scala.pickling.functions$.unpickle(functions.scala:11)
    at sbt.serialization.JsonValue$$anonfun$parse$1.apply(SerializedValue.scala:104)
    at scala.util.Try$.apply(Try.scala:191)
    at sbt.serialization.JsonValue.parse(SerializedValue.scala:104)
    at sbt.protocol.BuildValue.value(Values.scala:11)
    at sbt.protocol.TaskSuccess.resultWithCustomThrowable(Values.scala:65)
    at sbt.protocol.TaskResult$class.result(Values.scala:56)
    at sbt.protocol.TaskSuccess.result(Values.scala:62)
    at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:165)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:152)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
    at akka.dispatch.Mailbox.run(Mailbox.scala:221)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Play fork run has failed due to:
scala.pickling.PicklingException: error in unpickle of primitive unpickler 'java.lang.Integer':
tag in unpickle: 'scala.Nothing'
message:
Not a primitive: scala.Nothing, found JNothing
    at scala.pickling.pickler.PrimitivePickler.unpickle(Primitives.scala:31)
    at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler$macro$14$2$.unpickle(Serializers.scala:73)
    at scala.pickling.Unpickler$class.unpickleEntry(Pickler.scala:79)
    at play.forkrun.protocol.Serializers$PlayForkrunProtocolForkConfigUnpickler$macro$14$2$.unpickleEntry(Serializers.scala:73)
    at scala.pickling.functions$.unpickle(functions.scala:11)
    at sbt.serialization.JsonValue$$anonfun$parse$1.apply(SerializedValue.scala:104)
    at scala.util.Try$.apply(Try.scala:191)
    at sbt.serialization.JsonValue.parse(SerializedValue.scala:104)
    at sbt.protocol.BuildValue.value(Values.scala:11)
    at sbt.protocol.TaskSuccess.resultWithCustomThrowable(Values.scala:65)
    at sbt.protocol.TaskResult$class.result(Values.scala:56)
    at sbt.protocol.TaskSuccess.result(Values.scala:62)
    at play.forkrun.ForkRun$$anonfun$settingUp$1.applyOrElse(ForkRun.scala:165)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at play.forkrun.ForkRun.aroundReceive(ForkRun.scala:152)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
    at akka.dispatch.Mailbox.run(Mailbox.scala:221)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by sergiuszkierat** [comment]
It is strange. I am not sure, but maybe this is related to [this](https://groups.google.com/d/msg/play-framework/oBvT6352--Y/nZxX9qk4AQAJ).

> I resolved this by deleting the target directory and doing a clean compile and run. I suspect the issue was a stale build, that didnt seem to get resolved by doing the standard clean and compile through the Play Web UI. Only deleting the target folder seemed to do the trick.

Could you clean target folder or even could you check to run activator in different directory?

**Comment by MarcinBurczak** [comment]
Remove

`fork in run := true`

from build.sbt

**Comment by sriramkp** [comment]
I started the activator ui from the application directory and its started working. 

Thanks a lot.
